### ISSUE TITLE
Dashboard: Add tuning knobs for S-Lift and Flipper position targets

### ISSUE THREAD

**Issue by binnur** [Spartronics4915/2018-POWERUP#15]
Dashboard: Add tuning knobs for S-Lift and Flipper position targets on dashboard -- this will be used to tune the potentiometer ranges

**Comment by dbadb** [comment]
i added the support on the dashboard side and described to josh how to get the numbers from the scissor lift.

Adding the dashboard side for flipper position... How may positions was it?  (2?)

**Comment by binnur** [comment]
At very least there would be 3 for flipper (also referred to as pivot arm): 
- hold (all the way flat on its back)
- place (might have various placement positions)
- pick (pick from the harvester)
